### ISSUE TITLE
Add ability to remove new line ending

### ISSUE THREAD

**Issue by kvpt** [jmeyers91/barro#2]
Hi,

Thanks for this project, it works really fine.
The only problem I have is related to formatting (enforced by linter in our project).
I am able to replace the double quote by single by changing template but I can't prevent the new line ending to be added.

Two solutions : 
- Move the new line in the template, so a custom template can also remove it (but this will be a breaking change for the users which use a custom template)
- Add a parameter to control this, but I think it's a shame to have to do that given that there is the possibility of defining a custom template

What do you think ?

**Comment by jmeyers91** [comment]
I like the first solution. I'll move the new line into the default template.

**Comment by jmeyers91** [comment]
Fixed in v1.1.4

**Comment by kvpt** [comment]
Thank you for the quick response and fix. 👍
